core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('summary/', views.OrderSummary.as_view(), name='summary'),
    path('product/<slug>/', views.ItemDetailView.as_view(), name='detail'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-single-item/<slug>/', views.remove_single_item, name='remove-single-item'),
    path('remove-item/<slug>/', views.remove_item, name='remove-item'),
    path('shipping-address/', views.ShippingAddressView.as_view(), name='shipping-address'),
    path('add-coupon/', views.CouponView.as_view(), name='add-coupon'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
]

frontend/models.py
from django.db import models
from django.shortcuts import reverse
from django.template.defaultfilters import slugify
from django_countries.fields import CountryField
from django.contrib.auth.models import User

from core import settings

CATEGORY_CHOICES = (
    ('C', 'Computer'),
    ('M', 'Mobile'),
    ('T', 'Tablet'),
)

LABEL_CHOICES = (
    ('N', 'New'),
    ('R', 'Refurbished'),
    ('U', 'Used'),

)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=5)
    label = models.CharField(choices=LABEL_CHOICES, max_length=30)
    slug = models.SlugField()
    description = models.TextField(blank=True, null=True)
    # image = models.ImageField(upload_to='items/%Y/%m/%d/', blank=True, default='images.jpeg')
    image = models.CharField(max_length=255, blank=True, null=True)
    item_url = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Item, self).save(*args, **kwargs)

    def get_discount_percent(self):
        discount_percent = 100 - ((self.discount_price * 100) / self.price)
        return discount_percent

    def get_item_url(self):
        return reverse('frontend:detail', kwargs={'slug': self.slug})

    def get_add_to_cart(self):
        return reverse('frontend:add-to-cart', kwargs={
            'slug': self.slug
        })

    def snip_description(self):
        return self.description[:30] + "..."

    # class Meta:
    #     ordering = ['-id']


class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} - {self.item.title}'

    def total_item_price(self):
        return self.quantity * self.item.price

    def total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def amount_saved(self):
        return self.total_item_price() - self.total_discount_item_price()

    def final_price(self):
        if self.item.discount_price:
            return self.total_discount_item_price()
        return self.total_item_price()


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_ref = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_request = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def total_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.final_price()

        if self.coupon:
            total -= self.coupon.amount
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment = models.CharField(max_length=100)
    country = CountryField(max_length=100, default='Ukraine')
    zip = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=20)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.pk}'

frontend/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


class ShippingAddressForm(forms.Form):
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'floatingInput',
        'placeholder': 'Street and house number'
    }))
    apartment = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'floatingApartment',
        'placeholder': 'Apartment'
    }))
    country = CountryField(blank_label='Select country').formfield(widget=CountrySelectWidget(attrs={
        'class': 'form-control',
        'id': 'floatingSelect',
        'placeholder': 'Select country',
        'aria-label': 'Select country'
    }))
    zip = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'floatingZip',
        'placeholder': 'Zip'
    }))


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Coupon code'
    }))

frontend/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View

from django.views.generic import DetailView, ListView

from .models import Item, OrderItem, Order, BillingAddress, Coupon, Payment
from .forms import ShippingAddressForm, CouponForm

import stripe
import random
import string
from django.conf import settings

stripe.api_key = settings.STRIPE_SECRET_KEY


def create_order_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=12))


class HomeView(ListView):
    model = Item
    paginate_by = 8
    template_name = 'frontend/home.html'


class ItemDetailView(DetailView):
    model = Item
    template_name = 'frontend/detail.html'

    # @method_decorator(login_required)
    # def dispatch(self, *args, **kwargs):
    #     return super(ItemDetailView, self).dispatch(*args, **kwargs)


@login_required(login_url='../account/login')
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    order_q = Order.objects.filter(user=request.user, ordered=False)

    if order_q.exists():
        order = order_q[0]

        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, 'Item added to your cart!')
            return redirect('frontend:summary')
        else:
            messages.info(request, 'Item added to your cart!')
            order.items.add(order_item)
            return redirect('frontend:summary')
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, 'Item added to your cart!')
        return redirect('frontend:summary')


class OrderSummary(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            current_order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': current_order
            }
            return render(self.request, 'frontend/summary.html', context=context)
        except ObjectDoesNotExist:
            messages.warning(self.request, 'You do not have an active orders')
            return redirect('/')

        return render(self.request, 'frontend/summary.html', context=context)


@login_required(login_url='../account/login')
def remove_single_item(request, slug):
    item = get_object_or_404(Item, slug=slug)

    order_q = Order.objects.filter(user=request.user, ordered=False)

    if order_q.exists():
        order = order_q[0]

        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)

            messages.info(request, 'Cart updated')
            return redirect('frontend:summary')
        else:
            messages.warning(request, 'Item was not in your cart')
            return redirect('frontend:detail', slug=slug)
    else:
        messages.warning(request, 'You do not have an active order')
        return redirect('frontend:detail', slug=slug)


@login_required(login_url='../account/login')
def remove_item(request, slug):
    item = get_object_or_404(Item, slug=slug)

    order_q = Order.objects.filter(user=request.user, ordered=False)

    if order_q.exists():
        order = order_q[0]

        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
            order.items.remove(order_item)

            messages.info(request, 'Cart updated')
            return redirect('frontend:summary')

        else:
            messages.warning(request, 'Item was not in your cart')
            return redirect('frontend:detail', slug=slug)

    else:
        messages.warning(request, 'You do not have an active order')
        return redirect('frontend:detail', slug=slug)


class ShippingAddressView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            form = ShippingAddressForm()
            context = {
                'form': form,
                'order': order,
                'couponform': CouponForm(),
                'display_coupon_form': True
            }
            return render(self.request, 'frontend/shipping-address.html', context=context)

        except ObjectDoesNotExist:
            messages.warning(self.request, 'You do not have an active order')
            return redirect('frontend:summary')

    def post(self, *args, **kwargs):
        form = ShippingAddressForm(self.request.POST or None)

        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                apartment = form.cleaned_data.get('apartment')
                country = form.cleaned_data.get('country')
                zip = form.cleaned_data.get('zip')

                billing_address = BillingAddress(
                    user=self.request.user,
                    street_address=street_address,
                    apartment=apartment,
                    country=country,
                    zip=zip
                )

                billing_address.save()
                order.billing_address = billing_address
                order.save()

                messages.info(self.request, 'Address added to order')

                return redirect('frontend:summary')
        except ObjectDoesNotExist:
            messages.warning(self.request, 'No active order')
            return redirect('frontend:summary')


def get_coupon(request, code):
    try:
        coupon = Coupon.objects.get(code=code)
        return coupon
    except ObjectDoesNotExist:
        messages.warning(request, "This coupon is not valid")
        # return redirect('frontend:shipping-address')
        return None


class CouponView(View):
    def post(self, *args, **kwargs):
        form = CouponForm(self.request.POST or None)
        if form.is_valid():
            try:
                code = form.cleaned_data.get('code')
                order = Order.objects.get(user=self.request.user, ordered=False)
                if get_coupon(self.request, code):
                    order.coupon = get_coupon(self.request, code)
                    order.save()
                    messages.success(self.request, "Coupon added")

                return redirect('frontend:shipping-address')

            except ObjectDoesNotExist:
                messages.success(self.request, "You do not have an active order")
                return redirect('frontend:shipping-address')


class PaymentView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        if order.billing_address:
            context = {
                'order': order,
                'display_coupon_form': False
            }
            return render(self.request, 'frontend/payment.html', context)
        else:
            messages.warning(self.request, 'Please add your billing address')
            return redirect('frontend:shipping-address')

    def post(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        token = self.request.POST.get('stripeToken')
        amount = int(order.total_price() * 100)

        try:
            charge = stripe.Charge.create(
                amount=amount,
                currency='usd',
                source=token,
                description='Payment from ecommerce-django'
            )
            payment = Payment()
            payment.stripe_charge_id = charge['id']
            payment.user = self.request.user
            payment.amount = order.total_price()
            payment.save()

            order_items = order.items.all()
            order_items.update(ordered=True)

            for item in order_items:
                item.save()

            order.ordered = True
            order.payment = payment

            order.order_ref = create_order_code()
            order.save()

            messages.success(self.request, 'Oredered successful')
            return redirect('/')

        except stripe.error.CardError as e:

            body = e.json_body
            err = body.get('error', {})
            messages.warning(self.request, f"{err.get('message')}")
            return redirect("/")
        except stripe.error.RateLimitError as e:
            messages.warning(self.request, "Rate Limit Error")
            return redirect("/")
        except stripe.error.InvalidRequestError as e:
            messages.warning(self.request, "Invalid parameters")
            print("Invalid parameters", e)
            print("the value is: ", amount)
            return redirect("/")
        except stripe.error.AuthenticationError as e:
            messages.warning(self.request, "Not authenticated")
            return redirect("/")
        except stripe.error.APIConnectionError as e:
            messages.warning(self.request, "Network Error")
            return redirect("/")
        except stripe.error.StripeError as e:
            print(e)

frontend/templates/frontend/cart_snippet.html
<h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge bg-dark text-white ms-1 rounded-pill">{{ order.items.count }}</span>
  </h4>

  <!-- Cart -->
  <ul class="list-group mb-3 z-depth-1">
      {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title }}</h6>
        <small class="text-muted">{{ order_item.item.snip_description }}</small>
      </div>
      <span class="text-muted">${{ order_item.final_price }}</span>
    </li>
    {% endfor %}

    {% if order.coupon %}

    <li class="list-group-item d-flex justify-content-between bg-light">
      <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
      </div>
      <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}

    <li class="list-group-item d-flex justify-content-between">
      <span>Total (USD)</span>
      <strong>${{ order.total_price }}</strong>
    </li>
  </ul>
  <!-- Cart -->

<!--promo code-->
{% if display_coupon_form %}
    <form action="{% url 'frontend:add-coupon' %}" method="post" autocomplete="off" class="container">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-addon">
                <button class="btn btn-info m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
{% endif %}

frontend/templates/frontend/detail.html
{% extends 'base.html' %}

{% block title %}
    ecom | {{ object.title }}
{% endblock %}


{% block content %}
    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                {#                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0"#}
                {#                                           src="{{ item.image.url }}" alt="..."/>#}
                {#                </div>#}
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0"
                                           src="{{ item.image }}" alt="..."/>
                </div>
                <div class="col-md-6">
                    {#                    <div class="small mb-1">SKU: BST-498</div>#}
                    <h1 class="display-5 fw-bolder">{{ item.title }}</h1>
                    <div class="fs-5 mb-5">
                        {% if item.discount_price %}
                            <span class="text-decoration-line-through">{{ item.price }} ₴</span>
                            <span>{{ item.discount_price }} ₴</span>
                        {% else %}
                            <span>{{ item.price }} ₴</span>
                        {% endif %}
                    </div>
                    <p class="lead">{{ item.description }}</p>

                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center">
                            <a class="btn btn-outline-dark mt-auto me-4" href="{% url 'frontend:home' %}">Continue
                                shopping</a>
                            <a class="btn btn-outline-dark mt-auto" href="{{ item.get_add_to_cart }}">Add to cart <i
                                    class="bi-cart-fill me-1"></i></a>

                        </div>
                    </div>


                </div>
            </div>
        </div>
    </section>

{% endblock %}

frontend/templates/frontend/home.html
{% extends 'base.html' %}

{% block title %}
    ecom | erge.one
{% endblock %}


{% block content %}

    <section>
        <div class="container px-4 px-lg-5 mt-1">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                {% for item in object_list %}
                    <div class="col-lg-3 col-sm-4 mb-3">
                        <div class="product-card ">

                            <div class="product-thumb">
                                {#                                <a href="{{ item.get_item_url }}"><img src="{{ item.image.url }}" alt=""/></a>#}
                                <a href="{{ item.get_item_url }}"><img src="{{ item.image }}" alt=""/></a>
                            </div>

                            <div class="product-details">
                                <h4><a href="{{ item.get_item_url }}">{{ item.title }}</a></h4>
                                <p>
                                    {{ item.description }}
                                </p>

                                <div class="product-bottom-details d-flex justify-content-between">
                                    {% if item.discount_price %}
                                        <div class="product-price"><small>{{ item.price }} ₴</small>
                                            {{ item.discount_price }} ₴
                                        </div>
                                    {% else %}
                                        <div class="product-price">{{ item.price }} ₴
                                        </div>
                                    {% endif %}

                                    <div class="product-links">
                                        <a href="{{ item.get_add_to_cart }}"><i
                                                class="fa-solid fa-cart-shopping"></i></a>
                                        <a href=""><i class="fa-regular fa-heart"></i></a>
                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>


        {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">

                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    <li class="mx-4 mt-2"> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} </li>

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}

                </ul>
            </nav>
        {% endif %}

    </section>

{% endblock %}

frontend/templates/frontend/shipping-address.html
{% extends 'base.html' %}

{% block title %} Ecom | Shipping address {% endblock title %}



{% block content %}
<section class="py-5 container">
   <div class="row">

       <div class="col-md-8">

           <h4 class="mb-4">Shipping Address</h4>

           {% if order.billing_address %}
           <p>You have already added the address! <i><b>{{ order.billing_address.street_address }}</b></i>, do you want to change?</p>
                <a href="" class="btn btn-warning">Change address</a>
                <a href="{% url 'frontend:payment' %}" class="btn btn-info">Proceed to checkout</a>
           {% else %}

           <form action="" method="post" autocomplete="off" class="container">
               {% csrf_token %}

               <div class="form-floating mb-3">
                  {{ form.street_address }}
                  <label for="floatingInput">Street and house number</label>
               </div>

               <div class="form-floating mb-3">
                  {{ form.apartment_address }}
                  <label for="floatingApartment">Apartment</label>
               </div>

               <div class="form-floating mb-3">
                  {{ form.country }}
                   <div class="invalid-feedback">Please select a valid country</div>
                  <label for="floatingSelect">Select country</label>
               </div>
               <div class="form-floating mb-3">
                  {{ form.zip }}
                  <label for="floatingZip">Zip code</label>
               </div>

                  <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

           </form>

           {% endif %}

       </div><!--md8-->

       <div class="col-md-4">
           {% include 'frontend/cart_snippet.html' %}
       </div>

   </div><!--container-->
</section>

{% endblock %}

frontend/templates/frontend/summary.html
{% extends 'base.html' %}

{% block title %}
    ecom | {{ object.title }}
{% endblock %}


{% block content %}
    <section class="py-5">

        <div class="container table-responsive">
            <h4>Order summary</h4>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">item</th>
                    <th scope="col">price</th>
                    <th scope="col">quantity</th>
                    <th scope="col">total price</th>

                </tr>
                </thead>
                <tbody>
                {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ order_item.item.title }}</td>

                        {% if order_item.item.discount_price %}
                            <td>{{ order_item.item.discount_price }} ₴</td>
                        {% else %}
                            <td>{{ order_item.item.price }} ₴</td>
                        {% endif %}

                        <td>
                            <a href="{% url 'frontend:remove-single-item' order_item.item.slug %}"><i
                                    class="bi bi-dash-circle mr-2"></i></a>
                            {{ order_item.quantity }}
                            <a href="{% url 'frontend:add-to-cart' order_item.item.slug %}"><i
                                    class="bi bi-plus-circle ml-2"></i></a>

                        </td>

                        {% if order_item.item.discount_price %}
                            <td>{{ order_item.total_discount_item_price }} ₴
                                <span class="badge  bg-success">Saving: {{ order_item.amount_saved|floatformat:2 }} ₴</span>
                            </td>
                        {% else %}
                            <td>{{ order_item.total_item_price }} ₴</td>
                        {% endif %}

                    </tr>

                {% endfor %}


                {% if object.total_price %}
                    <tr>
                        <td colspan="4"><b>Order total: </b></td>
                        <td><b>{{ object.total_price }} ₴</b></td>
                    </tr>
                {% endif %}

                <tr>
                    <td colspan="5">
                        <a href="{% url 'frontend:shipping-address' %}" class="btn btn-warning float-end">Proceed to
                            checkout</a>

                        <a href="{% url 'frontend:home' %}" class="btn btn-info float-end mr-2">Continue shopping</a>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
    </section>

{% endblock %}